image: python:3.7-buster
stages:
    - Lint
    - Build
    - Analysis

eslint:
  stage: Lint
  image: node
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js --ext .js appserver/

slim:
  stage: Build
  before_script:
      - pip install splunk-packaging-toolkit
      - apt update -y && apt install -y nodejs npm
  script:
      - cd appserver/static/visualizations/process_flow_diagram && npm install
      - npm run build  && cd ${CI_PROJECT_DIR}
      - mkdir /tmp/${CI_PROJECT_NAME}
      - git archive --format tar HEAD | tar -xC /tmp/${CI_PROJECT_NAME}
      - ls /tmp/${CI_PROJECT_NAME}
      - slim package -o ${CI_PROJECT_NAME}/ /tmp/${CI_PROJECT_NAME}
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ${CI_PROJECT_NAME}/*
    expire_in: 1 week


appinspect:
    stage: Analysis
    before_script:
      - wget --output-document splunk-appinspect.tar.gz https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
      - pip install splunk-appinspect.tar.gz 
    script:
      - splunk-appinspect inspect `ls ${CI_PROJECT_NAME}/*.tar.gz` --mode precert --included-tags cloud
