image: python:3.7
stages:
    - Analysis
    - Build

eslint:
  stage: Analysis
  image: node
  script:
    - npm i eslint
    - node_modules/eslint/bin/eslint.js appserver/

appinspect:
    stage: Analysis
    before_script:
      - wget --output-document splunk-appinspect.tar.gz https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
      - pip install splunk-appinspect.tar.gz 
    script:
      - mkdir /tmp/${CI_PROJECT_NAME}
      - git archive --format tar HEAD | tar -xC /tmp/${CI_PROJECT_NAME}
      - ls /tmp/${CI_PROJECT_NAME}
      - splunk-appinspect inspect /tmp/${CI_PROJECT_NAME} --mode precert --included-tags cloud

slim:
  stage: Build
  script:
      - pip install splunk-packaging-toolkit
      - mkdir /tmp/${CI_PROJECT_NAME}
      - git archive --format tar HEAD | tar -xC /tmp/${CI_PROJECT_NAME}
      - slim package -o ${CI_PROJECT_NAME}/ /tmp/${CI_PROJECT_NAME}
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_SHORT_SHA"
    paths:
      - ${CI_PROJECT_NAME}/*
    expire_in: 1 week
  except:
    - tags