image: python:3.7
stages:
    - appinspect
    - package

appinspect:
    stage: appinspect
    before_script:
      - wget --output-document splunk-appinspect.tar.gz https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
      - pip install splunk-appinspect.tar.gz 
    script:
      - mkdir /tmp/${CI_PROJECT_NAME}
      - git archive --format tar HEAD | tar -xC /tmp/${CI_PROJECT_NAME}
      - ls /tmp/${CI_PROJECT_NAME}
      - splunk-appinspect inspect /tmp/${CI_PROJECT_NAME} --mode precert --included-tags cloud

package_app:
  before_script:
    - export APP_VERSION=$(cat app.manifest| jq -r '.info.id.version')
    - export APP_NAME=$(cat app.manifest| jq -r '.info.id.name')
    - echo $APP_VERSION
  stage: package
  script:
      - pip install splunk-packaging-toolkit
      - mkdir /tmp/${CI_PROJECT_NAME}
      - git archive --format tar HEAD | tar -xC /tmp/${CI_PROJECT_NAME}
      - slim package /tmp/${CI_PROJECT_NAME}
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - $NAME-$APP_VERSION.tar.gz  # make this dynamic, pulling from app manifest
    expire_in: 1 week
