version: "3.6"

services:
  splunk:
    image: splunk/splunk:9.0.1
    container_name: process_flow_diagram_app_workbench
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=passw0rd
    ports:
      - 8000:8000
      - 8089:8089
    volumes:
      - './process_flow_diagram_app:/opt/splunk/etc/apps/process_flow_diagram_app'