name: Package

on: push

jobs:
  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: mkdir -p dist
      - run: >
            tar 
            --exclude process_flow_diagram_app/appserver/static/visualizations/process_flow_diagram/node_modules 
            --exclude process_flow_diagram_app/local 
            -zcvf 
            dist/app.tgz 
            process_flow_diagram_app

      - uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: dist/app.tgz
  appinspect:
    name: AppInspect Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          sudo apt-get install libxml2-dev libxslt1-dev
          python -m pip install http://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz
      - name: Run AppInspect
        run: |
          splunk-appinspect inspect process_flow_diagram_app --output-file appinspect.json
          exit `cat appinspect.json | jq '.summary.failure'`
