name: Package

on: push

jobs:
  package-slim:
    name: Package Using Slim Toolki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: mkdir -p dist
      - run: >
            tar 
            --exclude process_flow_diagram_app/appserver/static/visualizations/process_flow_diagram/node_modules 
            --exclude process_flow_diagram_app/local 
            -zcvf 
            dist/app.tgz 
            process_flow_diagram_app

      - uses: actions/upload-artifact@v2
        with:
          name: bundle
          path: dist/app.tgz
  run-appinspect:
    steps:
      - run: >
          curl -Ls https://download.splunk.com/misc/appinspect/splunk-appinspect-2.0.0.tar.gz -o appinspect-lastest.tar.gz
          mkdir appinspect-latest
          tar -zxvf appinspect-lastest.tar.gz -C appinspect-latest --strip-components=1
      - run: >
            cd appinspect-latest
            rm -rf venv
            sudo pip install --upgrade pip setuptools
            sudo pip install virtualenv
            virtualenv --python=/usr/bin/python3 --clear venv
            source venv/bin/activate
            pip install .
      - run: >
            cd appinspect-latest
            source venv/bin/activate
            splunk-appinspect inspect ~/dist/app.tgz --included-tags=cloud
